(function(){
  const SUPABASE_URL='https://ccqyreaanjhfhglmmgkn.supabase.co';
  const SUPABASE_KEY='sb_publishable_LHWzWXPoDCD0VBl1i6QeBg_uFXrS_yL';
  let sb=null;
  function init(){if(!(window.supabase&&window.supabase.createClient)){setTimeout(init,100);return;}sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);window.LASTCALL={sb};if(location.hash==='#stories')loadLiveStories();}
  function esc(s){return String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;')}
  function close(){document.getElementById('panel')?.classList.add('hidden')} window.closePanel=close;
  function show(html){const p=document.getElementById('panel'),c=document.getElementById('panelContent');if(!p||!c)return;c.innerHTML=html;p.classList.remove('hidden')}
  async function session(){if(!sb)return null;return (await sb.auth.getSession()).data.session}
  function authForm(mode){const sign=mode==='signin';show(`<div class="eyebrow">LAST CALL · Members</div><h1>${sign?'Sign in':'Become a free member'}</h1><p class="muted">${sign?'Welcome back.':'To keep the stories going, feel free to become a member.'}</p><div class="formbox"><label>Email</label><input id="lcEmail" type="email" autocomplete="email" placeholder="you@example.com"><label>Password</label><input id="lcPassword" type="password" autocomplete="${sign?'current-password':'new-password'}" placeholder="${sign?'Password':'Create a password'}">${sign?'':'<label>Display name (optional)</label><input id="lcName" type="text" placeholder="Anonymous">'}<button class="btn primary" id="lcAuthBtn">${sign?'Sign in':'Become a free member →'}</button><p id="lcAuthMsg" class="note"></p><p class="note">It’s completely FREE to join. No subscription. No fees. Just good stories.</p></div>`);document.getElementById('lcAuthBtn').onclick=async()=>{const email=document.getElementById('lcEmail').value.trim(),password=document.getElementById('lcPassword').value,msg=document.getElementById('lcAuthMsg');if(!email||!password){msg.textContent='Please enter your email and password.';return}msg.textContent='Working…';let r=sign?await sb.auth.signInWithPassword({email,password}):await sb.auth.signUp({email,password,options:{data:{display_name:document.getElementById('lcName')?.value.trim()||'Anonymous'}}});if(r.error){msg.textContent=r.error.message;return}if(!sign&&!r.data.session){msg.textContent='Account created. Check your email to confirm it, then sign in.';return}msg.textContent='You’re in.';setTimeout(close,600)};}
  function writeForm(){show(`<div class="eyebrow">LAST CALL · Write a Story</div><h1>Tell us your story.</h1><p class="write-intro">Have a story from behind the bar? We'd love to hear it.</p><p class="privacy">Funny, strange, heartwarming, unforgettable — whatever stayed with you. No pressure, no drama required. You can post anonymously.</p><div class="formbox"><label>Story title (optional)</label><input id="lcTitle" placeholder="Give it a title, if you like"><label>Your story</label><textarea id="lcBody" autofocus placeholder="Start writing…"></textarea><label>Category</label><select id="lcCategory" style="width:100%;background:#11110f;border:1px solid rgba(215,182,93,.35);color:#f4eddf;padding:11px;margin:6px 0 13px;font:14px Georgia"><option>Closing Time</option><option>After Hours</option><option>Bar Wisdom</option><option>Staff Hours</option></select><label>City / country (optional)</label><input id="lcLocation" placeholder="e.g. Dublin, Ireland"><label>Display name (optional)</label><input id="lcDisplay" placeholder="Anonymous"><label><input id="lcAnon" type="checkbox" checked style="width:auto;margin-right:8px"> Post anonymously</label><br><button class="btn primary" id="lcPublish">Publish story →</button><p id="lcWriteMsg" class="note"></p><p class="note">Stories are submitted for review before public publication.</p></div>`);document.getElementById('lcPublish').onclick=submitStory}
  async function submitStory(){const body=document.getElementById('lcBody').value.trim(),title=document.getElementById('lcTitle').value.trim(),cat=document.getElementById('lcCategory').value,loc=document.getElementById('lcLocation').value.trim(),display=document.getElementById('lcDisplay').value.trim(),anon=document.getElementById('lcAnon').checked,msg=document.getElementById('lcWriteMsg');if(body.length<20){msg.textContent='Give us a little more of the story — at least 20 characters.';return}msg.textContent='Publishing…';const s=await session();let city=null,country=null;if(loc){const p=loc.split(',').map(x=>x.trim()).filter(Boolean);city=p[0]||null;country=p.slice(1).join(', ')||null}const {error}=await sb.from('stories').insert({author_id:s?.user?.id||null,title:title||'Untitled story',body,category:cat,city,country,anonymous_name:anon?'Anonymous':(display||null),status:'pending'});if(error){msg.textContent=error.message;return}msg.textContent='Story submitted. Thanks for adding to LAST CALL — it is now in the review queue.';setTimeout(close,1200)}
  function searchForm(){show('<div class="eyebrow">LAST CALL · Search</div><h1>Find a story</h1><div class="formbox"><input id="lcSearch" placeholder="Search stories, cities or categories"><div id="lcSearchResults" class="story-list"><p class="note">Start typing to search live stories.</p></div></div>');document.getElementById('lcSearch').oninput=searchLive}
  async function searchLive(){const q=document.getElementById('lcSearch').value.trim(),box=document.getElementById('lcSearchResults');if(!q){box.innerHTML='<p class="note">Start typing to search live stories.</p>';return}const {data,error}=await sb.from('stories').select('id,title,category,city,country,created_at').eq('status','published').or(`title.ilike.%${q}%,body.ilike.%${q}%,city.ilike.%${q}%,country.ilike.%${q}%,category.ilike.%${q}%`).order('created_at',{ascending:false}).limit(20);if(error){box.innerHTML='<p class="note">Search is unavailable right now.</p>';return}box.innerHTML=data?.length?data.map(storyRow).join(''):'<p class="note">No published stories found.</p>'}
  function storyRow(s){return `<div class="story-row" onclick="openLiveStory('${esc(s.id)}')"><strong>${esc(s.title)}</strong><span>${esc(s.category)} · ${esc([s.city,s.country].filter(Boolean).join(', ')||'Worldwide')}</span></div>`}
  window.openLiveStory=async function(id){const {data,error}=await sb.from('stories').select('id,title,body,category,city,country,anonymous_name').eq('id',id).eq('status','published').single();if(error||!data)return;const {count}=await sb.from('reactions').select('*',{count:'exact',head:true}).eq('story_id',id);const s=await session();let reacted=false;if(s){const r=await sb.from('reactions').select('story_id').eq('story_id',id).eq('user_id',s.user.id).maybeSingle();reacted=!!r.data}show(`<div class="eyebrow">${esc(data.category)} · LAST CALL</div><h1>${esc(data.title)}</h1><p class="muted">${esc([data.city,data.country].filter(Boolean).join(', ')||'Worldwide')} · ${esc(data.anonymous_name||'Anonymous')}</p><div class="story-row" style="cursor:default"><span style="font:14px Georgia;color:#f4eddf;line-height:1.65;white-space:pre-wrap">${esc(data.body)}</span></div><div class="story-row" onclick="reactLive('${id}',${reacted})"><strong>🍺 ${reacted?'You reacted':'React to this story'}</strong><span>${count||0} reactions</span></div>`)}
  window.reactLive=async function(id,reacted){const s=await session();if(!s){authForm('signin');return}if(reacted)await sb.from('reactions').delete().eq('story_id',id).eq('user_id',s.user.id);else await sb.from('reactions').insert({story_id:id,user_id:s.user.id,kind:'drink'});openLiveStory(id)}
  async function loadLiveStories(){if(!sb)return;const {data}=await sb.from('stories').select('id,title,category,city,country,created_at').eq('status','published').order('created_at',{ascending:false}).limit(12);if(!data?.length)return;const cols=document.querySelectorAll('.columns .card');if(cols[2])cols[2].innerHTML='<h3>◷ Latest Stories</h3>'+data.slice(0,3).map(storyRow).join('')}
  window.openPanel=function(type){if(type==='signin')return authForm('signin');if(type==='join')return authForm('join');if(type==='write')return writeForm();if(type==='search')return searchForm();if(type==='about')return show('<div class="eyebrow">LAST CALL</div><h1>Irish roots. Worldwide stories.</h1><p class="muted">LAST CALL is a home for the funny, wild, heartfelt and unforgettable moments that happen behind the bar — from Ireland to everywhere.</p><p class="muted">Every bar has a story. If yours stayed with you, we\'d love to hear it.</p>')};
  init();
})();